version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin public.ecr.aws
  build:
    commands:
      - echo "Source version $CODEBUILD_SOURCE_VERSION"
      - docker build --build-arg version=$IMAGE_TAG -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG public.ecr.aws//$IMAGE_REPO_NAME:$IMAGE_TAG
  # post_build:
  #   commands:
  #     - echo Build completed on `date`
  #     - echo Pushing the Docker image...
  #     - docker push public.ecr.aws//$IMAGE_REPO_NAME:$IMAGE_TAG